from __future__ import annotations

import argparse
from pathlib import Path
import sys

import pandas as pd


def main() -> int:
    p = argparse.ArgumentParser(description="Build local G4 feature cache from placed raw NMC data.")
    p.add_argument("--base-dir", default=".")
    p.add_argument("--raw-root", default="data/raw/NMC_SAMSUNG_INR_18650_2Ah")
    p.add_argument("--out-dir", default="data/cache/g4_features")
    p.add_argument("--feature-set", default="paper_g4_all_ema")
    args = p.parse_args()

    base_dir = Path(args.base_dir).resolve()
    if str(base_dir) not in sys.path:
        sys.path.insert(0, str(base_dir))

    from soc_decomp.nmc_branchbands_experiment import (
        NMCBranchBandsConfig,
        build_feature_frames,
        estimate_r0_by_temperature,
        find_csv_files,
        write_start_audit,
    )
    from soc_decomp.nmc_vit_feature_lstm_experiment import (
        add_vit_engineered_features,
        feature_columns,
        write_input_schema,
        write_leakage_audit,
    )

    raw_root = base_dir / args.raw_root
    out_dir = base_dir / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg = NMCBranchBandsConfig(
        base_dir=base_dir,
        raw_root=raw_root,
        train_profiles=("DST", "US06", "BJDST"),
        test_profiles=("FUDS",),
        window_len=50,
        stride=3,
        hidden_size=128,
        layers=6,
        kernel_size=5,
        dropout=0.06,
    )
    files = find_csv_files(raw_root)
    raw_source_columns = list(pd.read_csv(files[0], nrows=1).columns)
    write_start_audit(files, out_dir / "file_start_audit.csv")
    r0_df = estimate_r0_by_temperature(files, cfg.train_profiles)
    r0_df.to_csv(out_dir / "r0_train_profile_estimates.csv", index=False)
    frames = add_vit_engineered_features(build_feature_frames(cfg, files, r0_df))
    feature_cols = feature_columns(args.feature_set)
    write_input_schema(feature_cols, out_dir / "feature_schema_g4.csv")
    write_leakage_audit(feature_cols, raw_source_columns, out_dir / "no_cc_audit_g4.csv")

    rows = []
    for split, split_frames in frames.items():
        for i, frame in enumerate(split_frames):
            cols = [c for c in ["file_name", "trajectory_id", "temperature", "drive_cycle", "end_index", "SOC_physical"] + feature_cols if c in frame.columns]
            rel = Path(split) / f"{i:03d}_{frame['trajectory_id'].iloc[0]}.csv.gz"
            target = out_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            frame[cols].to_csv(target, index=False, compression="gzip")
            rows.append({"split": split, "relative_path": rel.as_posix(), "rows": len(frame), "columns": len(cols)})
    pd.DataFrame(rows).to_csv(out_dir / "feature_cache_manifest.csv", index=False)
    (out_dir / "ema_causality_report.md").write_text(
        "# EMA Causality Report\n\n"
        "G4 EMA channels are generated by one-sided recurrences inside each trajectory. "
        "No future samples, SOC inputs, cumulative Ah, or trajectory progress inputs are selected.\n",
        encoding="utf-8",
    )
    print(f"Wrote G4 feature cache to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

