from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


TEMP_ORDER = (0.0, 25.0, 45.0)


def set_manuscript_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "Times New Roman",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.titlesize": 13,
            "axes.labelsize": 12,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 10,
        }
    )


def plot_main_heatmap(details: pd.DataFrame, out_png: Path, out_pdf: Path, min_count: int, dpi: int) -> None:
    details = details[details["n_samples"].ge(min_count)].copy()
    details["SOC_IQR_percent"] = details["SOC_IQR_fraction"] * 100.0

    max_vbin = int(details["voltage_bin"].max())
    max_ibin = int(details["current_bin"].max())
    v_bins = np.arange(max_vbin + 1)
    i_bins = np.arange(max_ibin + 1)

    cmap = plt.get_cmap("magma").copy()
    cmap.set_bad("white")

    fig, axes = plt.subplots(1, len(TEMP_ORDER), figsize=(11.8, 3.65), sharey=True)
    image = None
    for ax, temp in zip(axes, TEMP_ORDER):
        d = details[details["temperature_C"].eq(temp)]
        pivot = d.pivot_table(
            index="current_bin",
            columns="voltage_bin",
            values="SOC_IQR_percent",
            aggfunc="mean",
        ).reindex(index=i_bins, columns=v_bins)
        image = ax.imshow(
            np.ma.masked_invalid(pivot.to_numpy()),
            origin="lower",
            aspect="auto",
            interpolation="nearest",
            cmap=cmap,
            vmin=0.0,
            vmax=10.0,
        )
        ax.text(
            0.03,
            0.94,
            f"{int(temp)} °C",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=11,
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.78, "pad": 1.5},
        )
        ax.set_xlabel("Voltage bin")
        ax.grid(False)
        for spine in ax.spines.values():
            spine.set_linewidth(0.8)
    axes[0].set_ylabel("Current bin")

    fig.subplots_adjust(left=0.055, right=0.905, bottom=0.20, top=0.86, wspace=0.18)
    if image is not None:
        cbar = fig.colorbar(image, ax=axes, location="right", fraction=0.028, pad=0.035)
        cbar.set_label("SOC IQR (%SOC)")
        cbar.set_ticks([0, 2, 4, 6, 8, 10])

    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=dpi)
    fig.savefig(out_pdf)
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replot manuscript Figure 3 raw V-I SOC IQR heatmap.")
    parser.add_argument(
        "--details",
        default="paper_ema_analysis_package/section2_measurement_structure/tables/table_s2_raw_vi_bin_details.csv",
        help="Raw V-I bin detail table generated by the Section 2 measurement-structure analysis.",
    )
    parser.add_argument(
        "--out-png",
        default="paper_ema_analysis_package/section2_measurement_structure/figures/Figure_3_raw_vi_soc_iqr_heatmap_by_temp_main.png",
    )
    parser.add_argument(
        "--out-pdf",
        default="paper_ema_analysis_package/section2_measurement_structure/figures/Figure_3_raw_vi_soc_iqr_heatmap_by_temp_main.pdf",
    )
    parser.add_argument("--min-count", type=int, default=50)
    parser.add_argument("--dpi", type=int, default=650)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    set_manuscript_style()
    details = pd.read_csv(args.details)
    plot_main_heatmap(
        details=details,
        out_png=Path(args.out_png),
        out_pdf=Path(args.out_pdf),
        min_count=args.min_count,
        dpi=args.dpi,
    )


if __name__ == "__main__":
    main()
